namespace Nest.Application.Consts;

public class UserRoleConsts
{
    public const string Admin = "Admin";
    public const string User = "User";
    public const string SuperAdmin = "SuperAdmin";
    public const string Moderator = "Moderator";
    public const string Basic = "Basic";
    public const string Guest = "Guest";
    public const string Manager = "Manager";
    public const string Developer = "Developer";
    public const string Tester = "Tester";
    public const string Support = "Support";
    public const string Sales = "Sales";
    public const string Marketing = "Marketing";
    public const string Customer = "Customer";
    public const string Supplier = "Supplier";
    public const string Partner = "Partner";
    public const string Vendor = "Vendor";
    public const string Distributor = "Distributor";
    public const string Reseller = "Reseller";
    public const string Agent = "Agent";
    public const string Broker = "Broker";
    public const string Dealer = "Dealer";
    public const string Merchant = "Merchant";
    public const string Buyer = "Buyer";
    public const string Seller = "Seller";
    public const string CustomerService = "CustomerService";
    public const string Accountant = "Accountant";
    public const string Finance = "Finance";
    public const string HR = "HR";
    public const string IT = "IT";
    public const string Legal = "Legal";
    public const string Logistics = "Logistics";
    public const string Operations = "Operations";
    public const string Procurement = "Procurement";
    public const string Quality = "Quality";
    public const string RnD = "RnD";
    public const string Security = "Security";
    public const string Warehouse = "Warehouse";
    public const string AdminAssistant = "AdminAssistant";
    public const string Executive = "Executive";
    public const string ManagerAssistant = "ManagerAssistant";
    public const string Director = "Director";
    public const string CEO = "CEO";
    public const string COO = "COO";
    public const string CTO = "CTO";
    public const string CFO = "CFO";
    public const string CMO = "CMO";
    public const string CIO = "CIO";
    public const string CISO = "CISO";
    public const string CRO = "CRO";
    public const string CDO = "CDO";
    public const string CSO = "CSO";
}